# Generated by Django 5.0 on 2023-12-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.holiday'),
        ),
        migrations.DeleteModel(
            name='Holidays',
        ),
    ]
