# Generated by Django 5.0 on 2023-12-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_month_holiday_mounth_alter_holiday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='type_holiday',
            field=models.CharField(choices=[('D', 'по дате'), ('W', 'по дню недели')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
