# Generated by Django 5.0 on 2023-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Доп.инф-ция'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Повод'),
        ),
    ]
