# Generated by Django 5.0 on 2023-12-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_holiday_description_alter_holiday_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Повод'),
        ),
    ]
