# Generated by Django 5.0 on 2023-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_holiday_date_alter_holiday_day_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='type_holiday',
            field=models.CharField(choices=[('D', 'по дате'), ('W', 'по дню недели')], max_length=2),
        ),
    ]
