# Generated by Django 5.0 on 2023-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_holiday_type_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='mounth',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='type_holiday',
            field=models.CharField(choices=[('D', 'по дате'), ('W', 'по дню недели')], max_length=2, verbose_name='Тип праздника'),
        ),
    ]
